title: Zacharie Esperanza # your name (or website title) here
logo: "/images/TDOV.PNG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Just an Animator who tried out Programming
  <br><br>
  Emphasis on "tried"
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
